version: '3.4'
networks:
  webappdeploynetwork:
services:
  webappdeployDB:
    container_name: webappdeployDB
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8002:1433
    hostname: mssql
    environment: 
      SA_PASSWORD: Password123
      ACCEPT_EULA: 'Y'
    volumes:
      - mssqlvolume:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
    user: root
    networks:
      - webappdeploynetwork
  webappdeploy:
    container_name: webappdeploy
    ports:
      - 8001:80
    image: ${DOCKER_REGISTRY-}webappdeploy
    build:
      context: .
      dockerfile: WebAppDeploy/Dockerfile
    depends_on:
      - webappdeployDB
    networks:
      - webappdeploynetwork

volumes:
  mssqlvolume:
